site_name: Laser Theory Notes
site_url: https://wyrdhy.github.io/Laser_Theory/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - Part A · Setup&Test: setup.md
  - Part B · Resonator Coupler: 
      - B1 Macroscopic Picture: 
        - 1 Rate Equation Model: Ring_Macro.md
        - 2 Splitting Resonance: Split_Resonance.md
        - 3 Resonator With A Drop Port:  Drop_Port.md
      - B2 Microscopic Picture:
        - 1 Driven Two Level System: Driven_TLS.md
        - 2 Microscopic Picture of Coupling: Ring_Micro.md
  - Part C · Leaky Mode Antenna: 
        - 1 Leaky Mode Antenna: Leaky_Mode_Antenna.md
        - 2 Measured Value and Model Revisited: THG_Power_Estimate.md

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - assets/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

extra_css:
  - assets/extra.css